
INSERT INTO category(title) VALUES('foo')
INSERT INTO category(title) VALUES('faa')
INSERT INTO category(title) VALUES('fee')


INSERT INTO REVIEW(CONTENT, IMAGE_URL, TITLE, CATEGORY_ID) VALUES('mama', 'baba', 'dada', 1)
INSERT INTO REVIEW(CONTENT, IMAGE_URL, TITLE, CATEGORY_ID) VALUES('khj', 'nhn', 'kkk', 1)
INSERT INTO REVIEW(CONTENT, IMAGE_URL, TITLE, CATEGORY_ID) VALUES('vxhjs', 'xbjhs', 'hhjshj', 1)

INSERT INTO REVIEW(CONTENT, IMAGE_URL, TITLE, CATEGORY_ID) VALUES('hshj', 'jbcjb', 'vjhsvj', 2)
INSERT INTO REVIEW(CONTENT, IMAGE_URL, TITLE, CATEGORY_ID) VALUES(' jksbk', 'bjksab', 'jbjhsbj', 2)
INSERT INTO REVIEW(CONTENT, IMAGE_URL, TITLE, CATEGORY_ID) VALUES('jksbk', 'nlkdnk', ' jdbj', 2)

INSERT INTO REVIEW(CONTENT, IMAGE_URL, TITLE, CATEGORY_ID) VALUES('nkjank', 'nlkank', 'kjwkj', 3)
INSERT INTO REVIEW(CONTENT, IMAGE_URL, TITLE, CATEGORY_ID) VALUES('njksank', 'kjank', 'knak', 3)
INSERT INTO REVIEW(CONTENT, IMAGE_URL, TITLE, CATEGORY_ID) VALUES('mlsl', 'nlkanl', 'nlkanlk', 3)




